/** Integration surface: public types and passive values; no engine or WordPress boot. */
export { EVENTS } from '../constants/events'
export type { IConfig } from '../interfaces/IConfig'
export type { IHeader } from '../interfaces/IHeader'
export type { IHeaderApp } from '../interfaces/IHeaderApp'
export type { IHeaderAppArgs } from '../interfaces/IHeaderAppArgs'
export type { IHeaderArgs } from '../interfaces/IHeaderArgs'
export type { IHeaderEventDetail } from '../interfaces/IHeaderEventDetail'
export type { IHeaderOptions } from '../interfaces/IHeaderOptions'
export type { IHeightObserverOptions } from '../interfaces/IHeightObserverOptions'
export type { IResolvedConfig } from '../interfaces/IResolvedConfig'
export type { IResolvedHeaderOptions } from '../interfaces/IResolvedHeaderOptions'
export type { IStickyOptions } from '../interfaces/IStickyOptions'
export type { THeaderEventName } from '../types/THeaderEventName'
export type { TToggleAttributes } from '../types/TToggleAttributes'
export type { TZoneMode } from '../types/TZoneMode'
